#!/bin/bash

cmd=$(which tmux)      # tmux path
cmdload=$(which tmuxp)      # tmux path

if [ -z $cmd ]; then
    echo "You need to install tmux."
    exit 1
fi

$cmd has -t $session 2> /dev/null

if [ $? != 0 ]; then
    $cmd new -d -n base-act -s $session "debug"
    $cmd new -d -n base-act -s $session "rokid"
    $cmd new -d -n base-act -s $session "temp"
    $cmd new -d -n base-act -s $session "default"
    #$cmd neww -n vim -t $session "zsh"
    #$cmd selectw -t $session:5
fi

$cmd att -t "rokid"


exit 0
